set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bg=black bold "
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""
set -g focus-events on
set -g mouse on

bind r source-file "~/.config/tmux/tmux.conf"
bind b set -g status
bind-key -n M-BSpace send-keys C-w
bind f run "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
bind g run "~/.config/scripts/open-github.sh"
bind t run "tmux neww ~/.config/scripts/time.sh"
bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents/notes"
bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents/projects"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/.config"
bind H run "~/.config/scripts/tmux-session-dispensary.sh ~"
bind M run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents/fax/master"
bind F run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents/fax"
bind B run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents/projects/BFMC"
# bind S run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects/stormy"
bind G neww -n "git" -S lazygit
bind o neww -S -n "BOOKMARKS" "nvim ~/bookmarks.csv"
bind e neww -S "nvim ~/bookmarks.csv"
bind E show-environment -g

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 
